### ISSUE TITLE
Throws exception with newest python version

### ISSUE THREAD

**Issue by riscie** [mota/i3-cycle#2]
Hi there

Seems like we moved to python 3.8.0 on arch. (Not a python dev myself). Now the app throws an exception on Launch:

```
Traceback (most recent call last):
  File "/usr/bin/i3-cycle", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'i3-cycle==1.0' distribution was not found and is required by the application
```

**Comment by riscie** [comment]
This most likely was an issue with my python setup. Consider it closed.
Thanks for the app, I use it everyday.

**Comment by dustbyte** [comment]
Glad it helps, thank you!
